Support for unknown variables
KovtunV/NoStringEvaluating pull request #4
Opened 2022-07-17 18:08 UTC by IvoTops

Implemented support for getting no value for a variable and treating it as null. Evaluating x + y will be null if either x or y is unknown and not throw an error anymore.

- IFunction has new property CanHandleNullArguments. Set to true if the function needs and/or recognizes IsNull values. Set to false to let the code set the result automatically to IsNull if any argument for the function is null.
- Added IfNull() and NullIf() functions to handle null values inside your formulas! =>  IfNull(x,-1)<0 will be TRUE if x is unknown at evaluation time.
- NULL as text in a formula will be interpreted as a variable set to null, so =>  IfNull(null,1)  will evaluate to 1
- Results from Calcxxx are now changed to reflect nullable outcomes => double?, bool?,..
- New EvaluatorValueTypeKey Null.  Can be checked with IsNull property
- default(EvaluatorValue) and default(InternalEvaluatorValue) will be treated as a null  value
- implicit conversions with double?, datetime?, .. added
- Added testcases for Null handling
- Added VariablesUsed() function with some overloads to get a list of the variables a formula contains
- Fixed equals comparison for non number values
- Added Benchmark for evaluating solely evaluating performance (common usecase=> parse once, evaluate again and again with new values)
 
Documentation is not yet updated

2022-07-17 19:02 UTC, KovtunV requested changes
Can't review other files until you fix namespace design

2022-07-17 19:02 UTC, KovtunV commented on NoStringEvaluating/Contract/INoStringEvaluator.cs
> +namespace NoStringEvaluating.Contract
Don't change design for namespaces, please, fix in all files. Have you rebased successfully?

2022-07-17 20:18 UTC, IvoTops commented
Ok, will fix. Is there an easy way to get the same settings in my visual
studio?

On Sun, 17 Jul 2022 at 21:02, Vitaly ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Can't review other files until you fix namespace design
> ------------------------------
>
> In
> NoStringEvaluating.Extensions.Microsoft.DependencyInjection/NoStringEvaluating.Extensions.Microsoft.DependencyInjection.csproj
> <https://github.com/KovtunV/NoStringEvaluating/pull/4#discussion_r922882385>
> :
>
> > @@ -37,4 +36,8 @@
>      </None>
>    </ItemGroup>
>
> +  <ItemGroup>
> +    <ProjectReference Include="..\NoStringEvaluating\NoStringEvaluating.csproj" />
> +  </ItemGroup>
>
> Don't change this file pls, it should refer to nuget
> ------------------------------
>
> In NoStringEvaluating/Contract/INoStringEvaluator.cs
> <https://github.com/KovtunV/NoStringEvaluating/pull/4#discussion_r922882650>
> :
>
> > @@ -5,416 +5,417 @@
>  using NoStringEvaluating.Models.Values;
>  using NoStringEvaluating.Nodes.Common;
>
> -namespace NoStringEvaluating.Contract;
> -
> -/// <summary>
> -/// Expression evaluator
> -/// </summary>
> -public interface INoStringEvaluator
> +namespace NoStringEvaluating.Contract
>
> Don't change design for namespaces, please, fix in all files. Have you
> rebased successfully?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/KovtunV/NoStringEvaluating/pull/4#pullrequestreview-1041172708>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA5YHTTOTPZMZXSZ4BQNEFLVURKFZANCNFSM532DWHSQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-07-17 20:27 UTC, KovtunV commented
> Ok, will fix. Is there an easy way to get the same settings in my visual studio?

To change namespace design? Yes, it should be in Visual Studio

2022-07-21 11:41 UTC, IvoTops commented
To rebase I fetched upstream from the master and that has the 'old' namespace design.  If I change the namespace design in visual studio and apply that it will also apply all my other code formatting settings. I see no option in vs to selectively apply only  the namespace design change. Could you run your coding style settings over the pull request and re-commit?

2022-07-22 05:42 UTC, KovtunV commented
> To rebase I fetched upstream from the master and that has the 'old' namespace design. If I change the namespace design in visual studio and apply that it will also apply all my other code formatting settings. I see no option in vs to selectively apply only the namespace design change. Could you run your coding style settings over the pull request and re-commit?

is it possible? Think will make MR to your master branch with these fixes

2022-07-23 13:22 UTC, merged

2022-10-11 08:33 UTC, IvoTops commented
If you think that works better please do that. I have been on GitHub for a
while but have only recently started contributing and using PR and such.

On Fri, Jul 22, 2022, 07:42 Vitaly ***@***.***> wrote:

> To rebase I fetched upstream from the master and that has the 'old'
> namespace design. If I change the namespace design in visual studio and
> apply that it will also apply all my other code formatting settings. I see
> no option in vs to selectively apply only the namespace design change.
> Could you run your coding style settings over the pull request and
> re-commit?
>
> is it possible? Think will make MR to your master branch with these fixes
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/KovtunV/NoStringEvaluating/pull/4#issuecomment-1192204041>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA5YHTVSKOWO2CHMONC6EALVVIYDLANCNFSM532DWHSQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>